// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfY29yJoPvlPVnbsCxwOCwI3tlDNF-H5o',
    appId: '1:918102071387:web:dba2cb6b1814036578877e',
    messagingSenderId: '918102071387',
    projectId: 'to-do-df0d0',
    authDomain: 'to-do-df0d0.firebaseapp.com',
    storageBucket: 'to-do-df0d0.firebasestorage.app',
    measurementId: 'G-EKQYC68GMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMNVZIAQirWjr2kf0Kl_OuWugWhW13U7Q',
    appId: '1:918102071387:android:eee525952cdb1cd578877e',
    messagingSenderId: '918102071387',
    projectId: 'to-do-df0d0',
    storageBucket: 'to-do-df0d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPghqXTffdLDAP9hjbaJaNWdQ2yGExF0',
    appId: '1:918102071387:ios:a5d904ba69951e8878877e',
    messagingSenderId: '918102071387',
    projectId: 'to-do-df0d0',
    storageBucket: 'to-do-df0d0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPghqXTffdLDAP9hjbaJaNWdQ2yGExF0',
    appId: '1:918102071387:ios:a5d904ba69951e8878877e',
    messagingSenderId: '918102071387',
    projectId: 'to-do-df0d0',
    storageBucket: 'to-do-df0d0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfY29yJoPvlPVnbsCxwOCwI3tlDNF-H5o',
    appId: '1:918102071387:web:500d807027d66e3e78877e',
    messagingSenderId: '918102071387',
    projectId: 'to-do-df0d0',
    authDomain: 'to-do-df0d0.firebaseapp.com',
    storageBucket: 'to-do-df0d0.firebasestorage.app',
    measurementId: 'G-WHXLE6SPNB',
  );
}
